### ISSUE TITLE
Input param does not work

### ISSUE THREAD

**Issue by kzap** [aisrael/actiondoc#6]
@aisrael 

You have an input param `path-to-action-yml` but the code does nothing with this. 😿 

https://github.com/aisrael/actiondoc/blob/main/action.yml#L14-L17

Companies may end up spending precious resources trying to use something as documented only to find out it doesn't work. 💰

**Comment by aisrael** [comment]
Should be fixed in https://github.com/aisrael/actiondoc/commit/3a87de3a136dcd89108477e6b28ec385517842db
